## pos-system

GET http://127.0.0.1:3030/api/purchases

POST http://127.0.0.1:3030/api/purchases
Content-Type: application/json

{
    "items": [
      {
        "name": "single donut hole",
        "price": 30,
        "quantity": 2
      },
      {
        "name": "half dozen donut hole",
        "price": 150,
        "quantity": 1
      }
    ]
}

POST http://127.0.0.1:3030/api/items
Content-Type: application/json

{
  "name": "single donut hole",
  "price": 30
}


POST http://127.0.0.1:3030/api/items
Content-Type: application/json

{
  "name": "half dozen donut hole",
  "price": 150
}