[database]
net_id = "0.0.0.0"
port = 5432
max_connections = 5
root_db_name = "postgres"
root_user = "postgres"
root_pwd = "postgres"
db_name = "postgres"
user = "pos_user"
pwd = "pos_user"

[webserver]
net_id = "0.0.0.0"
port = 8080
folder = "../frontend/web-folder/"
