[book]
title = "pos-system"
description = "a server and website for a point of sale system"
authors = ["Brighton Sikarskie <bsikar@tuta.io>"]
language = "en"
multilingual = false

[rust]
edition = "2021"

