name: Check backend tests

on:
  push:
    branches: [main, testing]
  pull_request:
    branches: [main, testing]

jobs:
  check-rust-code:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        rust: [stable, beta, nightly]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./backend/scripts

    steps:
    - uses: actions/checkout@v2

    - name: Install Python on macOS
      if: matrix.os == 'macOS-latest'
      uses: actions/setup-python@v2

    - name: Fix Python PATH on macOS
      if: matrix.os == 'macOS-latest'
      run: tee -a ~/.profile <<< 'export PATH="$pythonLocation/bin:$PATH"'

    - name: Check Clippy and Tests
      run: bash presubmit.sh
