name: Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-rust-code:
    strategy:
      matrix:
        # eventually will make this have windows and mac
        os: [ubuntu-latest]
        rust: [stable, beta, nightly]
        
    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Install Dependecies
      run: pip install -r requirements.txt
    - name: Run tests
      run: python test_backend.py
