name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: testing printing pwd
      run: echo $PWD
    - name: Cd into backend
      run: cd backend 
    - name: Build
      run: cargo build --verbose
    - name: Install Dependecies
      run: pip install -r requirements.txt
    - name: Run tests
      run: python test_backend.py
